FROM docker:dind-rootless as dind-source

FROM ubuntu:22.04

LABEL version="1.1" maintainer="NobleMajo (Majo Richter) <majo@coreunit.net>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils --no-install-recommends && \
    apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates \
        curl lxc iptables gnupg && \
    apt-get autoremove -y && \
    apt-get clean && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=dind-source /usr/local/bin/ /usr/local/bin/
COPY ./deamon.json /etc/docker/daemon.json

VOLUME /var/lib/docker
USER root

CMD ["dockerd"]
