name: Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: 10 13 * * 6

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: ./scripts/build.sh
      - name: Run built image
        run: ./scripts/start.sh
      - name: Check (max 5 times) if docker images is running
        run: for i in {1..5}; do docker exec --tty ${{ github.event.repository.name }} env TERM=xterm docker info && break || sleep 10; done
      - name: Clean up
        run: ./scripts/close.sh

  release:
    name: Release ubuntu(latest) dind
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to github
        uses: docker/login-action@v3 
        with:
          logout: true
          registry: docker.pkg.github.com
          username: ${{ GITHUB.ACTOR }}
          password: ${{ GITHUB.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.imagename }}:latest
            ${{ env.imagename }}:${{ GITHUB.SHA }}
            docker.pkg.github.com/${{ env.imagename }}:latest
            docker.pkg.github.com/${{ env.imagename }}:${{ GITHUB.SHA }}
