name: build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: ./build.sh
      - name: Run built image
        run: ./start.sh
      - name: Check (max 5 times) if docker images is running
        run: for i in {1..5}; do docker exec --tty ubuntu-dockerd env TERM=xterm docker info && break || sleep 10; done
      - name: Check if docker can pull alpine:latest inside of the container
        run: ./exec.sh docker pull alpine:latest

  release:
    name: Release docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push latest tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: majo418/ubuntudind:latest
          build-args: |
            DOCKERIMAGE_TAG=20.10.6-dind