name: Readme

on: 
  push:
    branches:
      - main
    paths: 
      - README.md
      - .github/workflows/readme.yml

jobs:
  docker-sync:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@master

      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_HUB_USERNAME }}
          pass: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          readme: README.md
          slug: ${{ github.GITHUB_REPOSITORY }}
          description: true
         
